function Hd = bpfilter(Fpass1, Fpass2, Fs)
%BPFILTER Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 27-Jul-2011 02:52:51
%

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
%Fs = 500;  % Sampling Frequency

N      = 10;  % Order
Fstop1 = Fpass1-2;    % First Stopband Frequency
%Fpass1 = 58;    % First Passband Frequency
%Fpass2 = 60;    % Second Passband Frequency
Fstop2 = Fpass2+2;    % Second Stopband Frequency
Wstop1 = 1;     % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 1;     % Second Stopband Weight
dens   = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
