function [b,a] = cheb_bpfilter(N, Fpass1,Fpass2,Apass, Fs)
%CHEBFILTER Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 12-Jul-2011 22:57:35
%

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
%Fs = 5000;  % Sampling Frequency

%N      = 100;  % Order
%Fpass1 = 1;    % First Passband Frequency
%Fpass2 = 500;  % Second Passband Frequency
%Apass  = 1;    % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');
[b,a] = sos2tf(Hd.sosMatrix);

% [EOF]
