function [b, a] = cheby2_bp(Fs, Fstop1, Fstop2)
%TESTF Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 14-Aug-2011 18:56:19
%

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
%Fs = 1000;  % Sampling Frequency

N      = 10;  % Order
%Fstop1 = 60;   % First Stopband Frequency
%Fstop2 = 62;   % Second Stopband Frequency
Astop  = 60;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');
[b,a] = sos2tf(Hd.sosMatrix);

% [EOF]
