global SZPREC_CURR_SZ
global SZPREC_CURR_WT
global SZPREC_CURR_T
global SZPREC_CURR_FREQS

%global SZPREC_CURR_XLIM

SZPREC_CURR_SZ = [];
SZPREC_CURR_WT = [];
SZPREC_CURR_T = [];
SZPREC_CURR_FREQS = [];
%SZPREC_CURR_XLIM = [];
